version: '3.8'
services:
  backend-admin:
    build:
      context: ./
      dockerfile: ./Dockerfile
    # 依赖项
    depends_on:
      - mysql
      - redis
    ports:
      - '3000:3000'
    # 容器重启策略
    restart: always
    networks:
      - app-network
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - app-network
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
