name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version
        id: set_version
        run: echo "::set-output name=version::$(date +'%Y%m%d%H%M%S')"

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to Alibaba Cloud Container Registry
      #   run: |
      #     echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin crpi-m0l230262f9a3pdl.cn-hangzhou.personal.cr.aliyuncs.com

      # - name: Build Docker image
      #   run: docker build -t crpi-m0l230262f9a3pdl.cn-hangzhou.personal.cr.aliyuncs.com/backend-admin/backend-admin:${{ steps.set_version.outputs.version }} .

      # - name: Push Docker image
      #   run: docker push crpi-m0l230262f9a3pdl.cn-hangzhou.personal.cr.aliyuncs.com/backend-admin/backend-admin:${{ steps.set_version.outputs.version }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            VERSION=${{ needs.build.outputs.version }}
            echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin crpi-m0l230262f9a3pdl.cn-hangzhou.personal.cr.aliyuncs.com
            docker-compose down && docker-compose pull && docker-compose up -d

          # docker pull crpi-m0l230262f9a3pdl.cn-hangzhou.personal.cr.aliyuncs.com/backend-admin/backend-admin:$VERSION
          # docker stop backend-admin 2>/dev/null || true
          # docker rm backend-admin 2>/dev/null || true
          # docker run -d --name backend-admin -p 3000:3000 crpi-m0l230262f9a3pdl.cn-hangzhou.personal.cr.aliyuncs.com/backend-admin/backend-admin:$VERSION
